### PR TITLE
Only Use Contextify When Required

### PR DESCRIPTION
**Pull request by jmurphyau**
I didn't realise my other PR was closed.. It seems they close themselves when the branch is exactly the same as the branch you're doing the PR against..

This PR adds the host option and uses/installs contextify only when it's needed (< node 0.10.x)

### CODE REVIEW

**Comment by tomdale** [comment]
Thanks @jmurphyau, can you move the host change into a separate PR? There are still a few commented out lines that should be cleaned up as well. Lastly, please use the style `isLegacyVM` instead of `isLegacyVM`. I will try to add a style guide so that isn't ambiguous. Thanks!

**Comment by jmurphyau** [comment]
@tomdale should look a bit better now

**Comment by jmurphyau** [comment]
Also, just an FYI - that plugin you mentioned about installing dependancies based on node version.. What it did was install a version of npm (which could be (and in my case was) a different version to the users current npm)  as a dependancy and then programatically install the dependancies.. The tried this and I had two issues with it:

1. It downloaded NPM as a dependancy.. You mentioned the length of time for building the contextify plugin - it almost seemed like downloading NPM took the same duration or longer.
2. NPM has been recently updated to show a progress bar sort of things rather than the previous style (I think it output a list of things that were happening when they were happening?) - the plugin used an NPM that produced the older style output.. It threw me off for a split second before realising what it was - especially since I was switching between node and NPM versions to test it out..

So instead of using that I've gone with a script that checks the `isLegacyVM` return result and produces an exit code based on that together with post install config that will install contextify if required

**Comment by tomdale** [comment]
Awesome! Thank you for all the hard work. I'm very excited about this change.

**Comment by tomdale** [comment]
@jmurphyau I had to revert this because it causes npm installs of this package to fail if it's not a legacy VM.

**Comment by jmurphyau** [comment]
really? hmm thats odd.. I use the latest node/npm - which fall into the category you mention - and it appeared to work fine for me.. Do you have any example of the error that appears

**Pull request merged**
